INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'RS', 'SRB', '688', 'Serbia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IR', 'IRN', '364', 'Iran (Islamic Republic Of)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IQ', 'IRQ', '368', 'Iraq');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IE', 'IRL', '372', 'Ireland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IL', 'ISR', '376', 'Israel');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IT', 'ITA', '380', 'Italy');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'JM', 'JAM', '388', 'Jamaica');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'JP', 'JPN', '392', 'Japan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KE', 'KEN', '404', 'Kenya');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KI', 'KIR', '296', 'Kiribati');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KP', 'PRK', '408', 'Korea, Democratic People''s Replublic of');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KR', 'KOR', '410', 'Korea, Republic of');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KW', 'KWT', '414', 'Kuwait');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KG', 'KGZ', '417', 'Kyrgyzstan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LA', 'LAO', '418', 'Lao People''s Democratic Republic');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LV', 'LVA', '428', 'Latvia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LB', 'LBN', '422', 'Lebanon');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LS', 'LSO', '426', 'Lesotho');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LR', 'LBR', '430', 'Liberia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LY', 'LBY', '434', 'Libyan Arab Jamahiriya');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LI', 'LIE', '438', 'Liechtenstein');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LT', 'LTU', '440', 'Lithuania');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LU', 'LUX', '442', 'Luxembourg');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MO', 'MAC', '446', 'Macau');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MK', 'MKD', '807', 'Macedonia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MG', 'MDG', '450', 'Madagascar');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MW', 'MWI', '454', 'Malawi');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MY', 'MYS', '458', 'Malaysia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MV', 'MDV', '462', 'Maldives');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ML', 'MLI', '466', 'Mali');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MT', 'MLT', '470', 'Malta');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MH', 'MHL', '584', 'Marshall Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MQ', 'MTQ', '474', 'Martinique');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MR', 'MRT', '478', 'Mauritania');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MU', 'MUS', '480', 'Mauritius');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'YT', 'MYT', '175', 'Mayotte');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MX', 'MEX', '484', 'Mexico');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FM', 'FSM', '583', 'Micronesia, Federated States of');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MD', 'MDA', '498', 'Moldova, Republic of');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MC', 'MCO', '492', 'Monaco');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MN', 'MNG', '496', 'Mongolia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MS', 'MSR', '500', 'Montserrat');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MA', 'MAR', '504', 'Morocco');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MZ', 'MOZ', '508', 'Mozambique');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MM', 'MMR', '104', 'Myanmar');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NA', 'NAM', '516', 'Namibia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NR', 'NRU', '520', 'Nauru');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NP', 'NPL', '524', 'Nepal');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NL', 'NLD', '528', 'Netherlands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AN', 'ANT', '530', 'Netherlands Antilles');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NC', 'NCL', '540', 'New Caledonia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NZ', 'NZL', '554', 'New Zealand');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NI', 'NIC', '558', 'Nicaragua');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NE', 'NER', '562', 'Niger');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NG', 'NGA', '566', 'Nigeria');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NU', 'NIU', '570', 'Niue');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NF', 'NFK', '574', 'Norfolk Island');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MP', 'MNP', '580', 'Northern Mariana Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'NO', 'NOR', '578', 'Norway');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'OM', 'OMN', '512', 'Oman');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PK', 'PAK', '586', 'Pakistan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PW', 'PLW', '585', 'Palau');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PS', 'PSE', '275', 'Palestinian Territory');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PA', 'PAN', '591', 'Panama');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PG', 'PNG', '598', 'Papua New Guinea');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PY', 'PRY', '600', 'Paraguay');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PE', 'PER', '604', 'Peru');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PH', 'PHL', '608', 'Philippines');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'JO', 'JOR', '400', 'Jordan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KZ', 'KAZ', '398', 'Kazakhstan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PN', 'PCN', '612', 'Pitcairn');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PL', 'POL', '616', 'Poland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PT', 'PRT', '620', 'Portugal');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PR', 'PRI', '630', 'Puerto Rico');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'QA', 'QAT', '634', 'Qatar');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'RE', 'REU', '638', 'Reunion');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'RO', 'ROU', '642', 'Romania');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'RU', 'RUS', '643', 'Russian Federation');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'RW', 'RWA', '646', 'Rwanda');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KN', 'KNA', '659', 'Saint Kitts And Nevis');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LC', 'LCA', '662', 'Saint Lucia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VC', 'VCT', '670', 'Saint Vincent And The Grenadines');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'WS', 'WSM', '882', 'Samoa');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SM', 'SMR', '674', 'San Marino');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ST', 'STP', '678', 'Sao Tome And Principe');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SA', 'SAU', '682', 'Saudi Arabia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SN', 'SEN', '686', 'Senegal');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SC', 'SYC', '690', 'Seychelles');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SL', 'SLE', '694', 'Sierra Leone');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SG', 'SGP', '702', 'Singapore');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SK', 'SVK', '703', 'Slovakia (Slovak Republic)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SI', 'SVN', '705', 'Slovenia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SB', 'SLB', '090', 'Solomon Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SO', 'SOM', '706', 'Somalia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ZA', 'ZAF', '710', 'South Africa');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GS', 'SGS', '239', 'South Georgia And The South Sandwich Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ES', 'ESP', '724', 'Spain');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'LK', 'LKA', '144', 'Sri Lanka');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SD', 'SDN', '736', 'Sudan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SR', 'SUR', '740', 'Suriname');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SJ', 'SJM', '744', 'Svalbard And Jan Mayen Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SZ', 'SWZ', '748', 'Swaziland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SE', 'SWE', '752', 'Sweden');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CH', 'CHE', '756', 'Switzerland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SY', 'SYR', '760', 'Syrian Arab Republic');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TW', 'TWN', '158', 'Taiwan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TJ', 'TJK', '762', 'Tajikistan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TZ', 'TZA', '834', 'Tanzania');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TH', 'THA', '764', 'Thailand');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TG', 'TGO', '768', 'Togo');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TK', 'TKL', '772', 'Tokelau');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TO', 'TON', '776', 'Tonga');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TT', 'TTO', '780', 'Trinidad And Tobago');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TN', 'TUN', '788', 'Tunisia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TR', 'TUR', '792', 'Turkey');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TM', 'TKM', '795', 'Turkmenistan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TC', 'TCA', '796', 'Turks And Caicos Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TV', 'TUV', '798', 'Tuvalu');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'UG', 'UGA', '800', 'Uganda');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'UA', 'UKR', '804', 'Ukraine');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HU', 'HUN', '348', 'Hungary');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IS', 'ISL', '352', 'Iceland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IN', 'IND', '356', 'India');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AE', 'ARE', '784', 'United Arab Emirates');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GB', 'GBR', '826', 'United Kingdom');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'US', 'USA', '840', 'United States');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'UM', 'UMI', '581', 'United States Minor Outlying Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'UY', 'URY', '858', 'Uruguay');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'UZ', 'UZB', '860', 'Uzbekistan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VU', 'VUT', '548', 'Vanuatu');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VE', 'VEN', '862', 'Venezuela');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VN', 'VNM', '704', 'Viet Nam');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VG', 'VGB', '092', 'Virgin Islands (British)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VI', 'VIR', '850', 'Virgin Islands (U.S.)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'WF', 'WLF', '876', 'Wallis And Futuna Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'EH', 'ESH', '732', 'Western Sahara');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'YE', 'YEM', '887', 'Yemen');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ZM', 'ZMB', '894', 'Zambia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ZW', 'ZWE', '716', 'Zimbabwe');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AF', 'AFG', '004', 'Afghanistan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AL', 'ALB', '008', 'Albania');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DZ', 'DZA', '012', 'Algeria');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AS', 'ASM', '016', 'American Samoa');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AD', 'AND', '020', 'Andorra');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AO', 'AGO', '024', 'Angola');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AI', 'AIA', '660', 'Anguilla');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AQ', 'ATA', '010', 'Antarctica');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AG', 'ATG', '028', 'Antigua And Barbuda');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AR', 'ARG', '032', 'Argentina');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AM', 'ARM', '051', 'Armenia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AW', 'ABW', '533', 'Aruba');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AU', 'AUS', '036', 'Australia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AT', 'AUT', '040', 'Austria');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AZ', 'AZE', '031', 'Azerbaijan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BS', 'BHS', '044', 'Bahamas');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BH', 'BHR', '048', 'Bahrain');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BD', 'BGD', '050', 'Bangladesh');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BB', 'BRB', '052', 'Barbados');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BY', 'BLR', '112', 'Belarus');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BE', 'BEL', '056', 'Belgium');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BZ', 'BLZ', '084', 'Belize');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BJ', 'BEN', '204', 'Benin');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BM', 'BMU', '060', 'Bermuda');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BT', 'BTN', '064', 'Bhutan');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BO', 'BOL', '068', 'Bolivia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BA', 'BIH', '070', 'Bosnia And Herzegowina');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BW', 'BWA', '072', 'Botswana');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BV', 'BVT', '074', 'Bouvet Island');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BR', 'BRA', '076', 'Brazil');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IO', 'IOT', '086', 'British Indian Ocean Territory');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BN', 'BRN', '096', 'Brunei Darussalam');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BG', 'BGR', '100', 'Bulgaria');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BF', 'BFA', '854', 'Burkina Faso');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BI', 'BDI', '108', 'Burundi');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KH', 'KHM', '116', 'Cambodia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CM', 'CMR', '120', 'Cameroon');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CA', 'CAN', '124', 'Canada');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CV', 'CPV', '132', 'Cape Verde');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KY', 'CYM', '136', 'Cayman Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CF', 'CAF', '140', 'Central African Republic');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TD', 'TCD', '148', 'Chad');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CL', 'CHL', '152', 'Chile');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CN', 'CHN', '156', 'China');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CX', 'CXR', '162', 'Christmas Island');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CC', 'CCK', '166', 'Cocos (Keeling) Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CO', 'COL', '170', 'Colombia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'KM', 'COM', '174', 'Comoros');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CG', 'COG', '178', 'Congo');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CD', 'COD', '180', 'Congo, Democratic Republic of th');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CK', 'COK', '184', 'Cook Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CR', 'CRI', '188', 'Costa Rica');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CI', 'CIV', '384', 'Cote D''Ivoire');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HR', 'HRV', '191', 'Croatia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CU', 'CUB', '192', 'Cuba');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CY', 'CYP', '196', 'Cyprus');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'CZ', 'CZE', '203', 'Czech Republic');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DK', 'DNK', '208', 'Denmark');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DJ', 'DJI', '262', 'Djibouti');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DM', 'DMA', '212', 'Dominica');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DO', 'DOM', '214', 'Dominican Republic');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'EC', 'ECU', '218', 'Ecuador');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'EG', 'EGY', '818', 'Egypt');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SV', 'SLV', '222', 'El Salvador');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GQ', 'GNQ', '226', 'Equatorial Guinea');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ER', 'ERI', '232', 'Eritrea');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'EE', 'EST', '233', 'Estonia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ET', 'ETH', '231', 'Ethiopia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FK', 'FLK', '238', 'Falkland Islands (Malvinas)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FO', 'FRO', '234', 'Faroe Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FJ', 'FJI', '242', 'Fiji');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FI', 'FIN', '246', 'Finland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'FR', 'FRA', '250', 'France');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GF', 'GUF', '254', 'French Guiana');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PF', 'PYF', '258', 'French Polynesia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TF', 'ATF', '260', 'French Southern Territories');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GA', 'GAB', '266', 'Gabon');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GM', 'GMB', '270', 'Gambia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GE', 'GEO', '268', 'Georgia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'DE', 'DEU', '276', 'Germany');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GH', 'GHA', '288', 'Ghana');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GI', 'GIB', '292', 'Gibraltar');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GR', 'GRC', '300', 'Greece');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GL', 'GRL', '304', 'Greenland');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GD', 'GRD', '308', 'Grenada');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GP', 'GLP', '312', 'Guadeloupe');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GU', 'GUM', '316', 'Guam');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GT', 'GTM', '320', 'Guatemala');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GN', 'GIN', '324', 'Guinea');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GW', 'GNB', '624', 'Guinea-Bissau');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GY', 'GUY', '328', 'Guyana');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HT', 'HTI', '332', 'Haiti');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HM', 'HMD', '334', 'Heard And Mc Donald Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HN', 'HND', '340', 'Honduras');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'HK', 'HKG', '344', 'Hong Kong');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ID', 'IDN', '360', 'Indonesia');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'AX', 'ALA', '248', 'Aland Islands');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'GG', 'GGY', '831', 'Guernsey');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'VA', 'VAT', '336', 'Holy See (Vatican City State)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'IM', 'IMN', '833', 'Isle of Man');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'JE', 'JEY', '832', 'Jersey');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'ME', 'MNE', '499', 'Montenegro');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'BL', 'BLM', '652', 'Saint Barthelemy');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'SH', 'SHN', '654', 'Saint Helena');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'MF', 'MAF', '663', 'Saint Martin (French Part)');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'PM', 'SPM', '666', 'Saint Pierre and Miquelon');
INSERT INTO country ( ID, alpha2, alpha3, numeric, NAME) VALUES (nextval('hibernate_sequence'), 'TL', 'TLS', '626', 'Timor-Leste');