create table AuditLogDetail (id int8 not null, attribute varchar(100) not null, message varchar(256), newValue varchar(4000), oldValue varchar(4000), record_id int8 not null, primary key (id));
create table AuditLogRecord (id int8 not null, createdDate timestamp not null, entityId int8 not null, entityName varchar(254) not null, transactionId int8 not null, type varchar(255) not null, username varchar(100) not null, primary key (id));
create table additional_attachments (id int8 not null, comments text, form_status varchar(255), status_date timestamp not null, flattened_pdf_id int8, form_type_id int8 not null, signed_pdf_id int8, registration_id int8 not null, primary key (id), unique (registration_id));
create table byte_data_source (discriminator varchar(31) not null, id int8 not null, resource_path varchar(255), data oid, primary key (id));
create table certification_type (id int8 not null, name varchar(255) not null, expires bool not null, sort_ranking int4, primary key (id), unique (name));
create table certified_specialty_board (id int8 not null, name varchar(255) not null, primary key (id), unique (name));
create table certified_specialty_type (id int8 not null, name varchar(255) not null, designation varchar(255) not null, board_id int8 not null, primary key (id), unique (name, board_id));
create table country (id int8 not null, alpha2 varchar(2) not null unique, alpha3 varchar(3) not null unique, name varchar(254) not null unique, numeric varchar(3) not null unique, primary key (id));
create table credential (discriminator varchar(31) not null, id int8 not null, effective_date date, expiration_date date, status varchar(10), certificateType varchar(255), country varchar(3), license_id varchar(255), state varchar(2), issuer_id int8, profile_id int8 not null, certified_specialty_type_id int8, file_id int8, certification_type_id int8, degree_type_id int8, license_type_id int8, primary key (id));
create table curriculum_vitae (id int8 not null, comments text, form_status varchar(255), status_date timestamp not null, flattened_pdf_id int8, form_type_id int8 not null, signed_pdf_id int8, registration_id int8 not null, primary key (id), unique (registration_id));
create table degree_type (id int8 not null, name varchar(255) not null, md_or_equivalent bool, sort_ranking int4, primary key (id), unique (name));
create table financial_disclosure (id int8 not null, comments text, form_status varchar(255), status_date timestamp not null, equity_in_sponsor bool, financial_interest bool, monetary_gain bool, no_financial_interest bool, other_sponsor_payments bool, flattened_pdf_id int8, form_type_id int8 not null, signed_pdf_id int8, registration_id int8 not null, primary key (id), unique (registration_id));
create table financial_disclosure_documentation (disclosure int8 not null, firebirdfile int8 not null, primary key (disclosure, firebirdfile));
create table firebird_file (id int8 not null, content_type varchar(254) not null, description varchar(1024), length int4, file_name varchar(254) not null, upload_date timestamp, byte_data_source_id int8 not null, primary key (id));
create table firebird_user (id int8 not null, accepted_eula bool, username varchar(100) not null unique, investigator_role_profile_id int8, keystore_file_id int8, person_id int8 not null, primary key (id));
create table form1572_irbs (form1572_id int8 not null, irb_id int8 not null, primary key (form1572_id, irb_id), unique (form1572_id, irb_id));
create table form1572_labs (form1572_id int8 not null, lab_id int8 not null, primary key (form1572_id, lab_id), unique (form1572_id, lab_id));
create table form1572_practicesites (form1572_id int8 not null, practice_site_id int8 not null, primary key (form1572_id, practice_site_id), unique (form1572_id, practice_site_id));
create table form_1572 (id int8 not null, comments text, form_status varchar(255), status_date timestamp not null, flattened_pdf_id int8, form_type_id int8 not null, signed_pdf_id int8, registration_id int8 not null, primary key (id), unique (registration_id));
create table form_type (id int8 not null, name varchar(255) not null, description varchar(1024), form_type_enum varchar(26) unique, investigator_default varchar(13) not null, signing_field varchar(255), subinvestigator_default varchar(13) not null, sample_id int8, template_id int8, primary key (id));
create table formphrc_certificate (formphrc int8 not null, certificate int8 not null, primary key (formphrc, certificate));
create table formphrc_submitted_certificate (formphrc int8 not null, submitted_training_certificate int8 not null, primary key (formphrc, submitted_training_certificate));
create table human_research_certificate_form (id int8 not null, comments text, form_status varchar(255), status_date timestamp not null, flattened_pdf_id int8, form_type_id int8 not null, signed_pdf_id int8, registration_id int8 not null, primary key (id), unique (registration_id));
create table investigator_profile (id int8 not null, clinical_research_experience_text text, organization_id int8, person_id int8, primary key (id));
create table investigatorprofile_file (investigatorprofile int8 not null, file int8 not null, primary key (investigatorprofile, file));
create table laboratory_certificate (id int8 not null, effective_date date, expiration_date date, type varchar(64), certificate_file_id int8, clinical_laboratory_id int8 not null, primary key (id));
create table license_type (id int8 not null, name varchar(255) not null, sort_ranking int4, primary key (id), unique (name));
create table organization (id int8 not null, ctep_id varchar(255) unique, email varchar(255) not null, name varchar(255) not null, nes_id varchar(255) not null unique, curation_status varchar(18) not null, phone_number varchar(255), city varchar(255), country varchar(3), delivery_address varchar(255), postal_code varchar(255), state_or_province varchar(50), street_address varchar(255), primary key (id));
create table organization_association (id int8 not null, organization_role_id int8 not null, profile_id int8 not null, primary key (id), unique (profile_id, organization_role_id));
create table organization_role (discriminator varchar(31) not null, id int8 not null, nes_id varchar(255), curation_status varchar(18) not null, roleType varchar(19) not null, cap_exemption varchar(14), ohrp_assurance_number varchar(255), organization_id int8, primary key (id));
create table person (id int8 not null, email varchar(50) not null, first_name varchar(50) not null, last_name varchar(50) not null, middle_name varchar(50), nes_id varchar(255) not null unique, curation_status varchar(18) not null, phone_number varchar(255), city varchar(255), country varchar(3), delivery_address varchar(255), postal_code varchar(255), state_or_province varchar(50), street_address varchar(255), prefix varchar(10), suffix varchar(10), primary key (id));
create table person_association (id int8 not null, type varchar(20) not null, person_id int8 not null, profile_id int8 not null, primary key (id), unique (profile_id, person_id, type));
create table protocol (id int8 not null, phase varchar(15) not null, protocol_number varchar(12) not null, protocol_title varchar(200) not null, lead_organization_id int8, sponsor_id int8 not null, primary key (id), unique (protocol_number, sponsor_id));
create table protocol_agent (id int8 not null, name varchar(255) not null, primary key (id), unique (name));
create table protocol_firebirdfile (protocol int8 not null, firebirdfile int8 not null, primary key (protocol, firebirdfile));
create table protocol_investigator_form_optionality (protocol_id int8 not null, optionality varchar(13), form_type_id int8 not null, primary key (protocol_id, form_type_id));
create table protocol_modification (id int8 not null, description varchar(255) not null, revision_id int8 not null, primary key (id));
create table protocol_protocolagent (protocol_id int8 not null, protocolagent_id int8 not null, primary key (protocol_id, protocolagent_id));
create table protocol_registration (discriminator varchar(31) not null, id int8 not null, comments text, investigator_comments text, invitation_change_date timestamp not null, invitation_status varchar(64) not null, last_submission_date date, status varchar(64) not null, status_date timestamp not null, investigator_profile_id int8 not null, protocol_id int8 not null, primary_registration_id int8, primary key (id), unique (protocol_id, investigator_profile_id, discriminator));
create table protocol_revision (id int8 not null, comment text not null, date timestamp, protocol_id int8 not null, primary key (id));
create table protocol_subinvestigator_form_optionality (protocol_id int8 not null, optionality varchar(13), form_type_id int8 not null, primary key (protocol_id, form_type_id));
create table registration_attachments (registration int8 not null, firebirdfile int8 not null, primary key (registration, firebirdfile));
create table registration_coordinator_role (id int8 not null, create_date timestamp not null, status varchar(255), status_date timestamp not null, investigator_id int8 not null, firebird_user_id int8 not null, primary key (id), unique (firebird_user_id, investigator_id));
create table root_keystore (id int8 not null, keystore_file_id int8, primary key (id));
create table sponsor_role (id int8 not null, delegate bool not null, sponsor_id int8 not null, firebird_user_id int8 not null, primary key (id));
create table state (id int8 not null, code varchar(3) not null, name varchar(50) not null, country_id int8 not null, primary key (id), unique (code, country_id), unique (name, country_id));
create table submitted_certificate (id int8 not null, certificate_type varchar(255) not null, certificate_effective_date date, certificate_expiration_date date, certificate_file_id int8 not null, original_certificate_id int8, primary key (id));
alter table AuditLogDetail add constraint AUDIT_DEATIL_RECORD_FK foreign key (record_id) references AuditLogRecord;
alter table additional_attachments add constraint registration_form_signed_pdf_fkey foreign key (signed_pdf_id) references firebird_file;
alter table additional_attachments add constraint form_form_type_fkey foreign key (form_type_id) references form_type;
alter table additional_attachments add constraint registration_form_flattened_pdf_fkey foreign key (flattened_pdf_id) references firebird_file;
alter table additional_attachments add constraint additional_attachments_registration_fkey foreign key (registration_id) references protocol_registration;
alter table certified_specialty_type add constraint certified_specialty_type_certified_specialty_board_fkey foreign key (board_id) references certified_specialty_board;
create index alpha3_idx on country (alpha3);
alter table credential add constraint certificate_firebird_file_fkey foreign key (file_id) references firebird_file;
alter table credential add constraint specialty_certifiedspecialtytype_fkey foreign key (certified_specialty_type_id) references certified_specialty_type;
alter table credential add constraint license_licensetype_fkey foreign key (license_type_id) references license_type;
alter table credential add constraint degree_degreetype_fkey foreign key (degree_type_id) references degree_type;
alter table credential add constraint certification_certificationtype_fkey foreign key (certification_type_id) references certification_type;
alter table credential add constraint credential_profile_fkey foreign key (profile_id) references investigator_profile;
alter table credential add constraint credential_organization_fkey foreign key (issuer_id) references organization;
alter table curriculum_vitae add constraint registration_form_signed_pdf_fkey foreign key (signed_pdf_id) references firebird_file;
alter table curriculum_vitae add constraint form_form_type_fkey foreign key (form_type_id) references form_type;
alter table curriculum_vitae add constraint registration_form_flattened_pdf_fkey foreign key (flattened_pdf_id) references firebird_file;
alter table curriculum_vitae add constraint curriculum_vitae_registration_fkey foreign key (registration_id) references protocol_registration;
alter table financial_disclosure add constraint registration_form_signed_pdf_fkey foreign key (signed_pdf_id) references firebird_file;
alter table financial_disclosure add constraint form_form_type_fkey foreign key (form_type_id) references form_type;
alter table financial_disclosure add constraint registration_form_flattened_pdf_fkey foreign key (flattened_pdf_id) references firebird_file;
alter table financial_disclosure add constraint financial_disclosure_registration_fkey foreign key (registration_id) references protocol_registration;
alter table financial_disclosure_documentation add constraint financial_disclosure_fkey foreign key (disclosure) references financial_disclosure;
alter table financial_disclosure_documentation add constraint firebirdfile_fkey foreign key (firebirdfile) references firebird_file;
alter table firebird_file add constraint byte_data_source_fkey foreign key (byte_data_source_id) references byte_data_source;
alter table firebird_user add constraint user_keystorefile_fkey foreign key (keystore_file_id) references firebird_file;
alter table firebird_user add constraint investigator_role_profile_fkey foreign key (investigator_role_profile_id) references investigator_profile;
alter table firebird_user add constraint firebird_user_person_fkey foreign key (person_id) references person;
alter table form1572_irbs add constraint form1572_fkey foreign key (form1572_id) references form_1572;
alter table form1572_irbs add constraint form1572_irb_fkey foreign key (irb_id) references organization;
alter table form1572_labs add constraint form1572_lab_fkey foreign key (lab_id) references organization;
alter table form1572_labs add constraint form1572_fkey foreign key (form1572_id) references form_1572;
alter table form1572_practicesites add constraint form1572_practicesite_fkey foreign key (practice_site_id) references organization;
alter table form1572_practicesites add constraint form1572_fkey foreign key (form1572_id) references form_1572;
alter table form_1572 add constraint registration_form_signed_pdf_fkey foreign key (signed_pdf_id) references firebird_file;
alter table form_1572 add constraint form_form_type_fkey foreign key (form_type_id) references form_type;
alter table form_1572 add constraint registration_form_flattened_pdf_fkey foreign key (flattened_pdf_id) references firebird_file;
alter table form_1572 add constraint form1572_registration_fkey foreign key (registration_id) references protocol_registration;
alter table form_type add constraint form_type_sample_fk foreign key (sample_id) references firebird_file;
alter table form_type add constraint form_type_template_fk foreign key (template_id) references firebird_file;
alter table formphrc_certificate add constraint certificate_fkey foreign key (certificate) references credential;
alter table formphrc_certificate add constraint formphrc_fkey foreign key (formphrc) references human_research_certificate_form;
alter table formphrc_submitted_certificate add constraint formphrc_fkey foreign key (formphrc) references human_research_certificate_form;
alter table formphrc_submitted_certificate add constraint submitted_certificate_fkey foreign key (submitted_training_certificate) references submitted_certificate;
alter table human_research_certificate_form add constraint registration_form_signed_pdf_fkey foreign key (signed_pdf_id) references firebird_file;
alter table human_research_certificate_form add constraint form_form_type_fkey foreign key (form_type_id) references form_type;
alter table human_research_certificate_form add constraint registration_form_flattened_pdf_fkey foreign key (flattened_pdf_id) references firebird_file;
alter table human_research_certificate_form add constraint human_research_certificate_registration_fkey foreign key (registration_id) references protocol_registration;
alter table investigator_profile add constraint investigatorprofile_organization_fkey foreign key (organization_id) references organization;
alter table investigator_profile add constraint investigatorprofile_person_fkey foreign key (person_id) references person;
alter table investigatorprofile_file add constraint file_fkey foreign key (file) references firebird_file;
alter table investigatorprofile_file add constraint investigatorprofile_fkey foreign key (investigatorprofile) references investigator_profile;
alter table laboratory_certificate add constraint laboratory_certificate_clinical_laboratory_fkey foreign key (clinical_laboratory_id) references organization_role;
alter table laboratory_certificate add constraint laboratory_certificate_firebird_file_fkey foreign key (certificate_file_id) references firebird_file;
alter table organization_association add constraint organization_association_organization_role_fkey foreign key (organization_role_id) references organization_role;
alter table organization_association add constraint organization_association_profile_fkey foreign key (profile_id) references investigator_profile;
alter table organization_role add constraint organization_role_organization_fkey foreign key (organization_id) references organization;
alter table person_association add constraint person_association_person_fkey foreign key (person_id) references person;
alter table person_association add constraint person_association_profile_fkey foreign key (profile_id) references investigator_profile;
alter table protocol add constraint protocol_lead_organization_fkey foreign key (lead_organization_id) references organization;
alter table protocol add constraint protocol_sponsor_fkey foreign key (sponsor_id) references organization;
create index protocol_agent_name_index on protocol_agent (name);
alter table protocol_firebirdfile add constraint protocol_fkey foreign key (protocol) references protocol;
alter table protocol_firebirdfile add constraint firebirdfile_fkey foreign key (firebirdfile) references firebird_file;
alter table protocol_investigator_form_optionality add constraint FK71C868C2F4A033C3 foreign key (form_type_id) references form_type;
alter table protocol_investigator_form_optionality add constraint protocol_investigator_form_optionality_protocol_fkey foreign key (protocol_id) references protocol;
alter table protocol_modification add constraint protocol_change_item_revision_fkey foreign key (revision_id) references protocol_revision;
alter table protocol_protocolagent add constraint protocol_fkey foreign key (protocol_id) references protocol;
alter table protocol_protocolagent add constraint protocolagent_fkey foreign key (protocolagent_id) references protocol_agent;
alter table protocol_registration add constraint primary_registration_fkey foreign key (primary_registration_id) references protocol_registration;
alter table protocol_registration add constraint registration_protocol_fkey foreign key (protocol_id) references protocol;
alter table protocol_registration add constraint registration_investigatorprofile_fkey foreign key (investigator_profile_id) references investigator_profile;
alter table protocol_revision add constraint protocolrevision_protocol_fkey foreign key (protocol_id) references protocol;
alter table protocol_subinvestigator_form_optionality add constraint FKEFF416B0F4A033C3 foreign key (form_type_id) references form_type;
alter table protocol_subinvestigator_form_optionality add constraint protocol_subinvestigator_form_optionality_protocol_fkey foreign key (protocol_id) references protocol;
alter table registration_attachments add constraint registration_fkey foreign key (registration) references additional_attachments;
alter table registration_attachments add constraint firebirdfile_fkey foreign key (firebirdfile) references firebird_file;
alter table registration_coordinator_role add constraint investigator_fkey foreign key (investigator_id) references investigator_profile;
alter table registration_coordinator_role add constraint registration_coordinator_role_user_fkey foreign key (firebird_user_id) references firebird_user;
alter table root_keystore add constraint user_keystorefile_fkey foreign key (keystore_file_id) references firebird_file;
alter table sponsor_role add constraint sponsor_role_organization_fkey foreign key (sponsor_id) references organization;
alter table sponsor_role add constraint sponsor_role_user_fkey foreign key (firebird_user_id) references firebird_user;
alter table state add constraint state_country_fkey foreign key (country_id) references country;
alter table submitted_certificate add constraint submitted_training_certificate_original_fkey foreign key (original_certificate_id) references credential;
alter table submitted_certificate add constraint submitted_training_certificate_firebird_file_fkey foreign key (certificate_file_id) references firebird_file;
create sequence hibernate_sequence;
