-- US State Codes
-- from http://www.usps.com/ncsc/lookups/abbr_state.txt
-- http://www.itl.nist.gov/fipspubs/fip5-2.htm
insert into state (id, name, code, country_id) values
(nextval('hibernate_sequence'), 'ALABAMA', 'AL', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'ALASKA', 'AK', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'AMERICAN SAMOA', 'AS', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'ARIZONA', 'AZ', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'ARKANSAS', 'AR', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'CALIFORNIA', 'CA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'COLORADO', 'CO', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'CONNECTICUT', 'CT', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'DELAWARE', 'DE', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'DISTRICT OF COLUMBIA', 'DC', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'FEDERATED STATES OF MICRONESIA', 'FM', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'FLORIDA', 'FL', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'GEORGIA', 'GA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'GUAM', 'GU', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'HAWAII', 'HI', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'IDAHO', 'ID', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'ILLINOIS', 'IL', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'INDIANA', 'IN', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'IOWA', 'IA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'KANSAS', 'KS', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'KENTUCKY', 'KY', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'LOUISIANA', 'LA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MAINE', 'ME', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MARSHALL ISLANDS', 'MH', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MARYLAND', 'MD', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MASSACHUSETTS', 'MA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MICHIGAN', 'MI', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MINNESOTA', 'MN', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MISSISSIPPI', 'MS', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MISSOURI', 'MO', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'MONTANA', 'MT', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEBRASKA', 'NE', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEVADA', 'NV', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEW HAMPSHIRE', 'NH', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEW JERSEY', 'NJ', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEW MEXICO', 'NM', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NEW YORK', 'NY', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NORTH CAROLINA', 'NC', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NORTH DAKOTA', 'ND', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'NORTHERN MARIANA ISLANDS', 'MP', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'OHIO', 'OH', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'OKLAHOMA', 'OK', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'OREGON', 'OR', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'PALAU', 'PW', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'PENNSYLVANIA', 'PA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'PUERTO RICO', 'PR', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'RHODE ISLAND', 'RI', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'SOUTH CAROLINA', 'SC', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'SOUTH DAKOTA', 'SD', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'TENNESSEE', 'TN', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'TEXAS', 'TX', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'UTAH', 'UT', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'U.S. MINOR OUTLYING ISLANDS', 'UM', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'VERMONT', 'VT', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'VIRGIN ISLANDS', 'VI', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'VIRGINIA', 'VA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'WASHINGTON', 'WA', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'WEST VIRGINIA', 'WV', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'WISCONSIN', 'WI', (select id from country where alpha2 = 'US')),
(nextval('hibernate_sequence'), 'WYOMING', 'WY', (select id from country where alpha2 = 'US'));





 